### ISSUE TITLE
5.3 Makefile

### ISSUE THREAD

**Issue by K0nkere** [K0nkere/kkr-mlops-project#8]
.

**Comment by K0nkere** [comment]
run
`git status`

Create **.gitignore** and paste there no needed files
`git add .` - add files to commit
git commit -m "..." - pre-commit will check and fix

**Comment by K0nkere** [comment]
[Other Hooks ](https://pre-commit.com/hooks.html)- from pre-commit-config.yaml

**Comment by K0nkere** [comment]
#### [Adding pre-commit hooks for isort](https://pycqa.github.io/isort/docs/configuration/pre-commit.html)

**Comment by K0nkere** [comment]
### [Adding pre-commit hooks for black](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/) >
```
repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.9
```

**Comment by K0nkere** [comment]
### [Adding pre-commit hooks for pylint](https://pylint.pycqa.org/en/latest/user_guide/installation/pre-commit-integration.html) google pre-commit pylint

**Comment by K0nkere** [comment]
#### [Pre-commit hook for pytest](https://stackoverflow.com/questions/64011304/running-pytest-as-a-pre-commit-hook-no-such-file-or-directory-issue) >
google pre-commit pytest
```
 - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: bash -c 'pytest'
        language: system
```
